name: sqllite_table_builder
description: Programmatically create SQL Lite tables.
version: 0.1.1
repository: https://github.com/ZAZPRO/sqllite_table_builder

environment:
  sdk: ^3.1.4

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
